extends: 'default'

rules:
  braces:
    max-spaces-inside: 1
    max-spaces-inside-empty: 1
    min-spaces-inside-empty: 1
    level: 'error'
  brackets:
    max-spaces-inside: 0
    min-spaces-inside: 0
    max-spaces-inside-empty: 0
    min-spaces-inside-empty: 0
    level: 'error'
  colons:
    max-spaces-after: 1
    level: 'error'
  commas:
    max-spaces-after: -1
    level: 'error'
  comments-indentation:
    level: 'error'
  comments:
    ignore-shebangs: true
    level: 'error'
    min-spaces-from-content: 1
    require-starting-space: true
  empty-lines:
    max: 2
    level: 'error'
  hyphens:
    max-spaces-after: 1
    level: 'error'
  indentation:
    spaces: 2
  key-duplicates: 'enable'
  line-length:
    max: 160
    level: 'warning'
  new-lines:
    type: 'unix'
  quoted-strings:
    quote-type: 'single'
    required: true
  truthy:
    allowed-values: ['true', 'false']
    level: 'error'
