[project]
name = "OctoPrint-BedCooldown"
version = "0.6.2"
description = "Turns off the bed heater toward the end of a print"
authors = [
    { name = "Ryan Finnie", email = "ryan@finnie.org" },
]
requires-python = ">=3,<4"
license = "MPL-2.0"

[project.entry-points."octoprint.plugin"]
bedcooldown = "octoprint_bedcooldown"

[project.urls]
Homepage = "https://github.com/rfinnie/OctoPrint-BedCooldown"

[tool.black]
line-length = 132

# https://pypi.org/project/Flake8-pyproject/
[tool.flake8]
max-line-length = 132
